### ISSUE TITLE
NoneType Error 

### ISSUE THREAD

**Issue by shaurya2904** [qiuqiangkong/audio_tagging_jdc#1]
Hi Quiquiang,

I thought it would be much more appropriate to raise  an issue here. 

I am using the dataset ( DCASE 2016 Task 4 dataset: http://www.cs.tut.fi/sgn/arg/dcase2016/task-audio-tagging
) you have mentioned above and using the unaltered codes in audio_tagging_jdc repository. But it is still leading to NoneType error.
Which I am unable to pin point as to what in the original code is preventing the prepared data from getting pushed to the layer.

The error is occuring while calling getloss function. For instance in main_dev_bob.py line 48
`(n_songs, n_chunk, n_out) = a8_node.shape `
is generating

> AttributeError: 'NoneType' object has no attribute 'shape'

I wanted to share screenshot of the error. If there can be a easier correspondence with you it would be really helpful.

Regards,
Shaurya2904

**Comment by qiuqiangkong** [comment]
Hi Shaurya,


    The problem is fixed. Please pull the latest code and it should run now.


Best wishes,


Qiuqiang

________________________________

**Comment by shaurya2904** [comment]
Hi Mr. Kong,
That was really helpful. 
The code is working fine it seems. 

Regards, 
Shaurya
